export const INITIATE = 'INITIATE';
export const SAVE_DATA_AS_JSON = 'SAVE_DATA_AS_JSON';
export const LOAD_JSON_FILE = 'LOAD_JSON_FILE';
export const LOAD_JCAMP_FILE = 'LOAD_JCAMP_FILE';
export const LOAD_MOL_FILE = 'LOAD_MOL_FILE';
export const LOAD_ZIP_FILE = 'LOAD_ZIP_FILE';
export const LOAD_JDF_FILE = 'LOAD_JDF_FILE';
export const ADD_PEAK = 'ADD_PEAK';
export const ADD_PEAKS = 'ADD_PEAKS';
export const DELETE_PEAK_NOTATION = 'DELETE_PEAK_NOTATION';
export const SHIFT_SPECTRUM = 'SHIFT_SPECTRUM';
export const SET_X_DOMAIN = 'SET_X_DOMAIN';
export const SET_Y_DOMAIN = 'SET_Y_DOMAIN';
export const SET_ORIGINAL_DOMAIN = 'SET_ORIGINAL_DOMAIN';
export const SET_WIDTH = 'SET_WIDTH';
export const SET_DIMENSIONS = 'SET_DIMENSIONS';
export const SET_SELECTED_TOOL = 'SET_SELECTED_TOOL';
export const SET_SELECTED_FILTER = 'SET_SELECTED_FILTER';
export const CHANGE_SPECTRUM_TYPE = 'CHANGE_SPECTRUM_TYPE';
export const SET_DATA = 'SET_DATA';
export const FULL_ZOOM_OUT = 'FULL_ZOOM_OUT';
export const CHANGE_VISIBILITY = 'CHANGE_VISIBILITY';
export const CHANGE_PEAKS_MARKERS_VISIBILITY =
  'CHANGE_PEAKS_MARKERS_VISIBILITY';
export const CHANGE_ACTIVE_SPECTRUM = 'CHANGE_ACTIVE_SPECTRUM';
export const CHANGE_SPECTRUM_COLOR = 'CHANGE_SPECTRUM_COLOR';
export const ADD_INTEGRAL = 'ADD_INTEGRAL';
export const DELETE_INTEGRAL = 'DELETE_INTEGRAL';
export const TOGGLE_REAL_IMAGINARY_VISIBILITY =
  'TOGGLE_REAL_IMAGINARY_VISIBILITY';
export const SET_ZOOM_FACTOR = 'SET_ZOOM_FACTOR';
export const ADD_MOLECULE = 'ADD_MOLECULE';
export const SET_MOLECULE = 'SET_MOLECULE';
export const DELETE_MOLECULE = 'DELETE_MOLECULE';
export const DELETE_SPECTRA = 'DELETE_SPECTRA';
export const CHANGE_SPECTRUM_DISPLAY_VIEW_MODE =
  'CHANGE_SPECTRUM_DISPLAY_VIEW_MODE';
export const SET_INTEGRAL_Y_DOMAIN = 'SET_INTEGRAL_Y_DOMAIN';
export const RESIZE_INTEGRAL = 'RESIZE_INTEGRAL';
export const BRUSH_END = 'BRUSH_END';
export const RESET_DOMAIN = 'RESET_X_DOMAIN';
export const CHANGE_INTEGRAL_ZOOM = 'CHANGE_INTEGRAL_ZOOM';
export const ENABLE_FILTER = 'ENABLE_FILTER';
export const DELETE_FILTER = 'DELETE_FILTER';
export const APPLY_ZERO_FILLING_FILTER = 'APPLY_ZERO_FILLING_FILTER';
export const APPLY_FFT_FILTER = 'APPLY_FFT_FILTER';
export const CALCULATE_MANUAL_PHASE_CORRECTION_FILTER =
  'CALCULATE_MANUAL_PHASE_CORRECTION_FILTER';
export const APPLY_MANUAL_PHASE_CORRECTION_FILTER =
  'APPLY_MANUAL_PHASE_CORRECTION_FILTER';
export const APPLY_AUTO_PHASE_CORRECTION_FILTER =
  'APPLY_AUTO_PHASE_CORRECTION_FILTER';
export const APPLY_ABSOLUTE_FILTER = 'APPLY_ABSOLUTE_FILTER';
export const SET_VERTICAL_INDICATOR_X_POSITION =
  'SET_VERTICAL_INDICATOR_X_POSITION';
export const AUTO_PEAK_PICKING = 'AUTO_PEAK_PICKING';
export const AUTO_RANGES_DETECTION = 'AUTO_RANGES_DETECTION';
export const AUTO_ZONES_DETECTION = 'AUTO_ZONES_DETECTION';
export const DELETE_RANGE = 'DELETE_RANGE';
export const SET_SELECTED_OPTIONS_PANEL = 'SET_SELECTED_OPTIONS_PANEL';
export const SET_LOADING_FLAG = 'SET_LOADING_FLAG';
export const RESET_SELECTED_TOOL = 'RESET_SELECTED_TOOL';
export const SET_SPECTRUMS_VERTICAL_ALIGN = 'SET_SPECTRUMS_VERTICAL_AlIGN';
export const SAVE_AS_SVG = 'SAVE_AS_SVG';
export const CHANGE_INTEGRAL_DATA = 'CHANGE_INTEGRAL_DATA';
export const EXPORT_DATA = 'EXPORT_DATA';
export const SET_PREFERENCES = 'SET_PREFERENCES';
export const SET_ACTIVE_TAB = 'SET_ACTIVE_TAB';
export const CHANGE_INTEGRAL_SUM = 'CHANGE_INTEGRAL_SUM';
export const ADD_BASE_LINE_ZONE = 'ADD_BASE_LINE_ZONE';
export const DELETE_BASE_LINE_ZONE = 'DELETE_BASE_LINE_ZONE';
export const APPLY_BASE_LINE_CORRECTION_FILTER =
  'APPLY_BASE_LINE_CORRECTION_FILTER';
export const SET_KEY_PREFERENCES = 'SET_KEY_PREFERENCES';
export const APPLY_KEY_PREFERENCES = 'APPLY_KEY_PREFERENCES';
export const CHANGE_RANGE_DATA = 'CHANGE_RANGE_DATA';
export const RESIZE_RANGE = 'RESIZE_RANGE';
export const CHANGE_RANGE_SUM = 'CHANGE_RANGE_SUM';
export const ADD_RANGE = 'ADD_RANGE';
export const SET_2D_LEVEL = 'SET_2D_LEVEL';
export const ADD_2D_ZONE = 'ADD_2D_ZONE';
export const DELETE_2D_ZONE = 'DELETE_2D_ZONE';
export const ADD_MISSING_PROJECTION = 'ADD_MISSING_PROJECTION';
export const SET_FILTER_SNAPSHOT = 'SET_FILTER_SNAPSHOT';
export const SET_SHOW_MULTIPLICITY_TREES = 'SET_SHOW_MULTIPLICITY_TREES';
export const CHANGE_ZONE_DATA = 'CHANGE_ZONE_DATA';
export const CHANGE_RANGE_RELATIVE = 'CHANGE_RANGE_RELATIVE';
export const CHANGE_INTEGRAL_RELATIVE = 'CHANGE_INTEGRAL_RELATIVE';
