dep: 'prod,dev'
reject:
  # https://github.com/cheminfo/nmrium/issues/3983
  - '@playwright/test'
  # Our plugins are not all compatible with v10
  - eslint
  # Not compatible with typescript-eslint
  - typescript
