dep: 'prod,dev'
reject:
  # Types are deeply broken between this package and nmrium
  - nmr-correlation
  # We're not ready for React 19 yet
  - react
  - react-dom
  - '@types/react'
  - '@types/react-dom'
  # @atlaskit/analytics-next-stable-react-context
  # The latest version strictly requires React ^16.8.0, while our project uses React 18.
  - '@atlaskit/pragmatic-drag-and-drop'
