dep: 'prod,dev'
reject:
  # Types are deeply broken between this package and nmrium
  - nmr-correlation
  # Version 5.1.0 has a bug: https://github.com/facebook/react/issues/31687
  # Remove from devDependencies when fixed.
  - eslint-plugin-react-hooks
  # We're not ready for React 19 yet
  - react
  - react-dom
  - '@types/react'
  - '@types/react-dom'
