dep: 'prod,dev'
reject:
  # Types are deeply broken between this package and nmrium
  - nmr-correlation
  # We're not ready for React 19 yet
  - react
  - react-dom
  - '@types/react'
  - '@types/react-dom'
