export const PEAK_PICKING = 'PEAK_PICKING';
export const SHIFT_SPECTRUM = "SHIFT_SPECTRUM";
export const LOADING_SPECTRUM ="LOADING_SPECTRUM";
export const SET_X_DOMAIN ="SET_X_DOMAIN";
export const SET_Y_DOMAIN ="SET_Y_DOMAIN";
export const SET_ORGINAL_DOMAIN ="SET_ORGINAL_DOMAIN";
export const SET_WIDTH ="SET_WIDTH";
export const SET_POINTER_COORDINATES ="SET_POINTER_COORDINATES";
export const SET_SELECTED_TOOL ="SET_SELECTED_TOOL";
export const CHANGE_SPECTRUM_TYPE ="CHANGE_SPECTRUM_TYPE";
export const SET_DATA ="SET_DATA";
export const FULL_ZOOM_OUT ="FULL_ZOOM_OUT";
export const CHANGE_VISIBILITY ="CHANGE_VISIBILITY";
export const CHNAGE_ACTIVE_SPECTRUM ="CHNAGE_ACTIVE_SPECTRUM";
export const CHNAGE_SPECTRUM_COLOR ="CHNAGE_SPECTRUM_COLOR";



