export const INITIATE = 'INITIATE';
export const SAVE_DATA_AS_JSON = 'SAVE_DATA_AS_JSON';
export const LOAD_JSON_FILE = 'LOAD_JSON_FILE';
export const LOAD_JCAMP_FILE = 'LOAD_JCAMP_FILE';
export const LOAD_MOL_FILE = 'LOAD_MOL_FILE';
export const PEAK_PICKING = 'PEAK_PICKING';
export const DELETE_PEAK_NOTATION = 'DELETE_PEAK_NOTATION';
export const SHIFT_SPECTRUM = 'SHIFT_SPECTRUM';
export const SET_X_DOMAIN = 'SET_X_DOMAIN';
export const SET_Y_DOMAIN = 'SET_Y_DOMAIN';
export const SET_ORIGINAL_DOMAIN = 'SET_ORIGINAL_DOMAIN';
export const SET_WIDTH = 'SET_WIDTH';
export const SET_DIMENSIONS = 'SET_DIMENSIONS';
export const SET_POINTER_COORDINATES = 'SET_POINTER_COORDINATES';
export const SET_SELECTED_TOOL = 'SET_SELECTED_TOOL';
export const CHANGE_SPECTRUM_TYPE = 'CHANGE_SPECTRUM_TYPE';
export const SET_DATA = 'SET_DATA';
export const FULL_ZOOM_OUT = 'FULL_ZOOM_OUT';
export const CHANGE_VISIBILITY = 'CHANGE_VISIBILITY';
export const CHANGE_PEAKS_MARKERS_VISIBILITY =
  'CHANGE_PEAKS_MARKERS_VISIBILITY';
export const CHANGE_ACTIVE_SPECTRUM = 'CHANGE_ACTIVE_SPECTRUM';
export const CHANGE_SPECTRUM_COLOR = 'CHANGE_SPECTRUM_COLOR';
export const ADD_INTEGRAL = 'ADD_INTEGRAL';
export const TOGGLE_REAL_IMAGINARY_VISIBILITY =
  'TOGGLE_REAL_IMAGINARY_VISIBILITY';
export const SET_ZOOM_FACTOR = 'SET_ZOOM_FACTOR';
export const ADD_MOLECULE = 'ADD_MOLECULE';
export const SET_MOLECULE = 'SET_MOLECULE';
export const DELETE_MOLECULE = 'DELETE_MOLECULE';
export const DELETE_SPECTRA = 'DELETE_SPECTRA';
export const CHANGE_SPECTRUM_DIPSLAY_VIEW_MODE =
  'CHANGE_SPECTRUM_DIPSLAY_VIEW_MODE';
export const SET_INTEGRAL_Y_DOMAIN = 'SET_INTEGRAL_Y_DOMAIN';
export const RESIZE_INTEGRAL = 'RESIZE_INTEGRAL';
export const BRUSH_END = 'BRUSH_END';
export const RESET_DOMAIN = 'RESET_X_DOMAIN';
