import { Action } from '../context/DispatchContext';

const ignoreActions = new Set<Partial<Action['type']>>([
  'INITIALIZE_NMRIUM',
  'APPLY_KEY_PREFERENCES',
  'BRUSH_END',
  'RESET_SELECTED_TOOL',
  'SET_KEY_PREFERENCES',
  'SET_LOADING_FLAG',
  'SET_SELECTED_TOOL',
  'SET_SPECTRUMS_VERTICAL_ALIGN',
  'SET_VERTICAL_INDICATOR_X_POSITION',
  'SET_DIMENSIONS',
  'SET_X_DOMAIN',
  'SET_Y_DOMAIN',
  'SET_ZOOM',
  'TOGGLE_REAL_IMAGINARY_VISIBILITY',
  'CALCULATE_MANUAL_PHASE_CORRECTION_FILTER',
  'CHANGE_SPECTRUM_DISPLAY_VIEW_MODE',
  'FULL_ZOOM_OUT',
  'SET_ACTIVE_TAB',
  'CHANGE_SPECTRUM_VISIBILITY',
  'CHANGE_SPECTRA_VISIBILITY_BY_NUCLEUS',
  'CHANGE_ACTIVE_SPECTRUM',
  'SET_MOUSE_OVER_DISPLAYER',
  'SHOW_J_GRAPH',
  'SHOW_MULTIPLICITY_TREES',
  'SHOW_RANGES_INTEGRALS',
  'CHANGE_FLOAT_MOLECULE_POSITION',
]);

function checkActionType(type: Action['type']): boolean {
  if (!ignoreActions?.has(type)) return true;
  return false;
}

export default checkActionType;
