import type { InnerWorkspace } from 'nmrium-core';

export const basic: InnerWorkspace = {
  label: 'Simple NMR analysis',
  visible: true,
  display: {
    panels: {
      spectraPanel: { display: true, visible: true, open: true },
      informationPanel: { display: true, visible: true, open: false },
      peaksPanel: { display: true, visible: true, open: false },
      integralsPanel: { display: true, visible: true, open: false },
      rangesPanel: { display: true, visible: true, open: false },
      structuresPanel: { display: true, visible: true, open: false },
      processingsPanel: { display: true, visible: true, open: false },
      zonesPanel: { display: true, visible: true, open: false },
    },
    toolBarButtons: {
      zoom: true,
      zoomOut: true,
      import: true,
      exportAs: true,
      spectraStackAlignments: true,
      spectraCenterAlignments: true,
      realImaginary: true,
      peakPicking: true,
      integral: true,
      zonePicking: true,
      rangePicking: true,
      slicing: true,
      apodization: true,
      zeroFilling: true,
      fft: true,
      phaseCorrection: true,
      baselineCorrection: true,
      autoRangeAndZonePicking: true,
      fftDimension1: true,
      fftDimension2: true,
    },
  },
};
