import type { InnerWorkspace } from '@zakodium/nmrium-core';

export const embedded: InnerWorkspace = {
  label: 'Embedded',
  display: {
    general: {
      experimentalFeatures: { display: true, visible: true },
      hidePanelOnLoad: true,
      hideHelp: true,
      hideLogs: true,
      hideMaximize: true,
      hideWorkspaces: true,
      hideGeneralSettings: true,
    },

    panels: {
      spectraPanel: { display: true, visible: true, open: true },
      informationPanel: { display: true, visible: true, open: false },
      peaksPanel: { display: true, visible: true, open: false },
      integralsPanel: { display: true, visible: true, open: false },
      rangesPanel: { display: true, visible: true, open: false },
      structuresPanel: { display: true, visible: true, open: false },
      processingsPanel: { display: true, visible: true, open: false },
      zonesPanel: { display: true, visible: true, open: false },
    },
    toolBarButtons: {
      peakPicking: true,
      baselineCorrection: true,
      exclusionZones: true,
      exportAs: true,
      fft: true,
      import: true,
      integral: true,
      multipleSpectraAnalysis: true,
      phaseCorrection: true,
      rangePicking: true,
      realImaginary: true,
      slicing: true,
      spectraCenterAlignments: true,
      spectraStackAlignments: true,
      apodization: true,
      zeroFilling: true,
      zonePicking: true,
      zoomOut: true,
      zoom: true,
      autoRangeAndZonePicking: true,
      fftDimension1: true,
      fftDimension2: true,
      apodizationDimension1: true,
      apodizationDimension2: true,
      phaseCorrectionTwoDimensions: true,
      zeroFillingDimension1: true,
      zeroFillingDimension2: true,
      inset: true,
    },
  },
};
