name: 'NodeSecure Continuous Integration'
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  validation:
    name: 'Validation'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: NodeSecure/ci-action@v1
        with:
          strategy: npm
          vulnerabilities: medium
          warnings: off
          reporters: console
